"""Added is_published field in quiz

Revision ID: 4314c990b2bd
Revises: c4524f901149
Create Date: 2025-10-12 15:20:48.591183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4314c990b2bd'
down_revision: Union[str, Sequence[str], None] = 'c4524f901149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('is_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'is_published')
    # ### end Alembic commands ###
