"""Created on delete constraints for foreign keys

Revision ID: 565b7e07cbe6
Revises: 4314c990b2bd
Create Date: 2025-10-12 16:08:18.472212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '565b7e07cbe6'
down_revision: Union[str, Sequence[str], None] = '4314c990b2bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('answers_question_id_fkey'), 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('quizzes_created_by_fkey'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('submissions_quiz_id_fkey'), 'submissions', type_='foreignkey')
    op.drop_constraint(op.f('submissions_student_id_fkey'), 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'submissions', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key(op.f('submissions_student_id_fkey'), 'submissions', 'users', ['student_id'], ['id'])
    op.create_foreign_key(op.f('submissions_quiz_id_fkey'), 'submissions', 'quizzes', ['quiz_id'], ['id'])
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key(op.f('quizzes_created_by_fkey'), 'quizzes', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key(op.f('answers_question_id_fkey'), 'answers', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
