"""Added total points column in Quiz model

Revision ID: 7bad48bb073d
Revises: fecd68c7d9f4
Create Date: 2025-10-12 20:29:49.666596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bad48bb073d'
down_revision: Union[str, Sequence[str], None] = 'fecd68c7d9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('total_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'total_points')
    # ### end Alembic commands ###
