"""Removed seleced option field from answer model

Revision ID: fecd68c7d9f4
Revises: 565b7e07cbe6
Create Date: 2025-10-12 16:46:25.875611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fecd68c7d9f4'
down_revision: Union[str, Sequence[str], None] = '565b7e07cbe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('answers_selected_option_id_fkey'), 'answers', type_='foreignkey')
    op.drop_column('answers', 'selected_option_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('selected_option_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('answers_selected_option_id_fkey'), 'answers', 'options', ['selected_option_id'], ['id'])
    # ### end Alembic commands ###
